apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  oneadmin-password: {{ .Values.opennebula.oneadminPassword | b64enc }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc }}

